// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Le0bica7lzLcz4hPyZLOKCd0uxibhnw',
    appId: '1:65569720205:web:a5c5a81a84f77667c09fc4',
    messagingSenderId: '65569720205',
    projectId: 'franq-store-4d5d5',
    authDomain: 'franq-store-4d5d5.firebaseapp.com',
    storageBucket: 'franq-store-4d5d5.firebasestorage.app',
    measurementId: 'G-TQXXDLJSHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp-4dawtIaO-CXsmGzCCMAgbUKcBTB3ko',
    appId: '1:65569720205:android:a501846ba0aedafac09fc4',
    messagingSenderId: '65569720205',
    projectId: 'franq-store-4d5d5',
    storageBucket: 'franq-store-4d5d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5Hab1Zqpw7-X3t0tEjo342SKy1UK4ys',
    appId: '1:65569720205:ios:47014e01f8385dd3c09fc4',
    messagingSenderId: '65569720205',
    projectId: 'franq-store-4d5d5',
    storageBucket: 'franq-store-4d5d5.firebasestorage.app',
    iosBundleId: 'com.example.franqStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5Hab1Zqpw7-X3t0tEjo342SKy1UK4ys',
    appId: '1:65569720205:ios:47014e01f8385dd3c09fc4',
    messagingSenderId: '65569720205',
    projectId: 'franq-store-4d5d5',
    storageBucket: 'franq-store-4d5d5.firebasestorage.app',
    iosBundleId: 'com.example.franqStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Le0bica7lzLcz4hPyZLOKCd0uxibhnw',
    appId: '1:65569720205:web:3fd7ac86495393fcc09fc4',
    messagingSenderId: '65569720205',
    projectId: 'franq-store-4d5d5',
    authDomain: 'franq-store-4d5d5.firebaseapp.com',
    storageBucket: 'franq-store-4d5d5.firebasestorage.app',
    measurementId: 'G-ZE2QXCTWFG',
  );
}
